Replace main build script with shell
Align multiple line error messages properly

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,6 +1,6 @@
-#!/usr/bin/env python3
+#!/bin/sh
 
-# build.py -- this file is part of gnukit.
+# build -- this file is part of gnukit.
 # Copyright (C) 2020 XNSC
 #
 # This program is free software: you can redistribute it and/or modify
@@ -16,6 +16,16 @@
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 
-from src import build
+# Wrapper shell script to run python build script
 
-build.build_all()
+[ -z "$PYTHON" ] && PYTHON=python3
+if [ -z "`$PYTHON --version 2>/dev/null`" ]; then
+    echo "error: $PYTHON is not installed or does not work" 2>&1
+    echo "       Please install python3 before running this script," 2>&1
+    echo "       or set the PYTHON environment variable to a working" 2>&1
+    echo "       python3 executable." 2>&1
+    exit 1
+fi
+
+cd "`dirname $0`/src"
+$PYTHON build.py
